mkmm: use tmpfs with tsave and trestore

diff --git a/mkmm b/mkmm
--- a/mkmm
+++ b/mkmm
@@ -8,7 +8,7 @@ _myname="mkmm"
 
 __usage(){
   cat << EOH
-mkmm [-vf] save|restore|clean|bleach [kver]
+mkmm [-vf] save|restore|tsave|trestore|clean|bleach [kver]
 
 mkmm is Moviuro's Kernel Module Manager intended to be used in an
 alpm-hook(5) to save and restore the running kernel's modules because pacman(8)
@@ -21,12 +21,17 @@ save       : use cp(1) to hardlink the kernel modules in a backup directory if
              they aren't already backed up (--archive --link)
 -f save    : remove the existing backup if it exists, then use cp(1) --force to
              hardlink the kernel modules in a backup directory
+tsave      : use cp(1) and tmpfs(5) to copy the kernel modules in a temporary
+             filesystem if it doesn't yet exist
+-f tsave   : remove the existing backup if it exists, then tsave
 restore    : use cp(1) to hardlink the backed-up kernel modules back in place if
              they aren't found
 -f restore : remove the existing modules if they are found, then use cp(1)
              --force to hardlink the backed-up kernel modules back in place
-clean      : rm(1) the backup directory
--f clean   : use rm --force
+trestore   : use bind mount(8) to move the tsave-d tmpfs(5) back in place if
+             needed
+-f trestore: remove the current modules' directory, then trestore
+clean      : remove the backup directory (rm(1) or umount && rmdir)
 bleach     : rm(1) -rf modules' directories that don't belong to a pacman(8)
              package, except for the currently running kernel
 -f bleach  : rm(1) -rf modules' directories that don't belong to a pacman(8)
@@ -42,20 +47,48 @@ https://github.com/saber-nyan/kernel-modules-hook
 EOH
 }
 
+# We handle regular directories and mountpoints too...
+__remove() {
+  : "${1?Missing target}"
+
+  if [[ -e "$1" ]]; then
+    if findmnt "$1" >/dev/null; then
+      umount "$1"
+      rmdir "$1"
+    else
+      rm --recursive --force "$1"
+    fi
+  fi
+}
+
 # __save kver [force]
 __save() {
   : "${1?Missing kver}"
   [[ -n "$2" ]] && _force="--force"
   _dest="/usr/lib/modules/$_myname-$1"
 
-  mkdir -p "$_dest"
   if ! [[ -e "$_dest" ]] || [[ -n "$_force" ]]; then
-    [[ -e "$_dest" ]] && rm --recursive --force "$_dest"
+    __remove "$_dest"
     cp --archive --link $_force -- \
      "/usr/lib/modules/$1/." "$_dest"
     _ret=$?
   fi
   exit "${_ret:-0}"
+}
+
+# __tsave kver [force]
+__tsave() {
+  : "${1?Missing kver}"
+  [[ -n "$2" ]] && _force="--force"
+  _dest="/usr/lib/modules/$_myname-$1"
+i
+  if ! [[ -e "$_dest" ]] || [[ -n "$_force" ]]; then
+    __remove "$_dest"
+    mkdir -p "$_dest"
+    mount -t tmpfs -o rw,nodev,nosuid,mode=755 tmpfs "$_dest"
+    cp -a "/usr/lib/modules/$1/." "$_dest" || exit 6
+    mount -o remount,ro "$_dest" || exit 7
+  fi
 }
 
 # __restore kver [force]
@@ -64,22 +97,53 @@ __restore() {
   [[ -n "$2" ]] && _force="--force"
   _dest="/usr/lib/modules/$1"
 
+  if ! [[ -e "/usr/lib/modules/$_myname-$1" ]]; then
+    printf '%s\n' "/usr/lib/modules/$_myname-$1 for restoring not found" >&2
+    exit 8
+  fi
+
   if ! [[ -e "$_dest" ]] || [[ -n "$_force" ]]; then
-    [[ -e "$_dest" ]] && rm --recursive --force "$_dest"
+    __remove "$_dest"
     cp --archive --link $_force -- \
-     "/usr/lib/modules/$_myname/$1" "$_dest"
+     "/usr/lib/modules/$_myname-$1" "$_dest"
     _ret=$?
   fi
   exit "${_ret:-0}"
 }
 
-# __clean [force]
+# __trestore kver [force]
+__trestore() {
+  : "${1?Missing kver}"
+  [[ -n "$2" ]] && _force="--force"
+  _dest="/usr/lib/modules/$1"
+
+  if ! [[ -e "/usr/lib/modules/$_myname-$1" ]]; then
+    printf '%s\n' "/usr/lib/modules/$_myname-$1 for restoring not found" >&2
+    exit 9
+  fi
+
+  if ! [[ -e "$_dest" ]] || [[ -n "$_force" ]]; then
+    __remove "$_dest"
+    mkdir "$_dest"
+    mount -o bind "/usr/lib/modules/$_myname-$1" "$_dest"
+    _ret=$?
+  fi
+  exit "${_ret:-0}"
+}
+
+# __clean kver [force]
 __clean() {
   : "${1?Missing kver}"
   [[ -n "$2" ]] && _force="--force"
+  _dest="/usr/lib/modules/$_myname-$1"
 
-  rm --recursive $_force -- "/usr/lib/modules/$_myname-$1"
-  exit $?
+  if ! [[ -e "/usr/lib/modules/$1" ]] && [[ -z "$_force" ]]; then
+    printf '%s\n' \
+     "/usr/lib/modules/$1 does not exist, are you sure you want to clean?" >&2
+    exit 10
+  fi
+
+  __remove "$_dest"
 }
 
 # __bleach [force]
@@ -91,7 +155,7 @@ __bleach() {
     if ! pacman -Qqo "$_moddir" >/dev/null 2>&1; then
       if [[ "$_moddir" != "/usr/lib/modules/$(uname -r)" ]] ||
          [[ -n "$_force" ]]; then
-        rm --recursive --force -- "$_moddir"
+        __remove "$_moddir"
         ((_ret+=$?))
       fi
     fi
@@ -114,7 +178,9 @@ _kver="${2:-"$(uname -r)"}"
 
 case "$1" in
   save) __save "$_kver" "$_force" ;;
+  tsave) __tsave "$_kver" "$_force" ;;
   restore) __restore "$_kver" "$_force" ;;
+  trestore) __trestore "$_kver" "$_force" ;;
   clean) __clean "$_kver" "$_force" ;;
   bleach) __bleach "$_force" ;;
   *) __usage >&2 ; exit 1 ;;
